$schema: http://json-schema.org/draft-07/schema#
title: Recipe Schema
description: Schema for structured recipe data
type: object

required:
  - title
  - components
  - total_time
  - serving_size
  - spice_index

properties:
  title:
    type: string
    description: The name of the recipe

  total_time:
    type: string
    description: Total time to prepare and cook the recipe
    examples:
      - 30 minutes
      - 1 hour 15 minutes
      - 2 hours

  serving_size:
    type: integer
    description: Number of servings this recipe makes
    minimum: 1

  image:
    type: string
    description: URL to an image of the recipe
    format: uri

  spice_index:
    type: string
    description: Heat level of the dish
    enum:
      - none
      - mild
      - medium
      - hot
      - extra hot

  tags:
    type: array
    description: Tags to categorize the recipe
    items:
      type: string
      description: A tag or category
    examples:
      - - Italian
        - pasta
        - vegetarian
      - - Indian
        - curry
        - chicken

  components:
    type: array
    description: Different components or parts of the recipe
    minItems: 1
    items:
      type: object
      required:
        - name
        - ingredients
        - method
      properties:
        name:
          type: string
          description: Name of the recipe component
        
        ingredients:
          type: array
          description: List of ingredients for this component
          minItems: 1
          items:
            type: object
            required:
              - item
              - quantity
            properties:
              item:
                type: string
                description: Name of the ingredient
              quantity:
                type: string
                description: Amount of the ingredient
        
        method:
          type: array
          description: Cooking instructions
          minItems: 1
          items:
            type: string
            description: A single step in the method

  plating:
    type: array
    description: Instructions for plating and serving
    items:
      type: string
      description: A plating instruction step